BLAH
Change-Id: Ic3f30d9fc0711e3d4ce5c7cc6d472c856c12e113

diff --git a/core/no_java_path/keytool b/core/no_java_path/keytool
--- a/core/no_java_path/keytool
+++ b/core/no_java_path/keytool
@@ -1,1 +1,4 @@
-java
+#!/bin/bash
+
+echo "Error: JAVA_NOT_REQUIRED=true, $(basename $0) is unavailable." 1>&2
+exit 1
